### ISSUE TITLE
Make it Responsive

### ISSUE THREAD

**Issue by wigzen** [wigzen/wigzen.io#3]
site is not responsive

**Comment by abitsalihu** [comment]
Hey @wigzen, I would like to help with this issue. :)

**Comment by wigzen** [comment]
Yeah sure

**Comment by abitsalihu** [comment]
@wigzen alright assign me to this, I'll work on it later today. :)

**Comment by wigzen** [comment]
Can't thank you enough  thank you so much for your work.
But how did you find this repo . I would love to do same
